services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments_dev
      POSTGRES_DB: payments_platform
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
